spring.application.name=tour-management

spring.datasource.url=jdbc:postgresql://localhost:5432/Booking_tour
spring.datasource.username=postgres
spring.datasource.password=ahihidocho1652

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Ollama Server
spring.ai.ollama.base-url=http://localhost:11434
# Tên model b?n ?ã t?i v? (ph?i kh?p chính xác tên trong Ollama app)
spring.ai.ollama.chat.options.model=llama3.1


spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# spring.ai.google.ai.chat.options.model=gemini-1.5-flash


logging.level.org.springframework.ai=DEBUG

